### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by lepapareil** [TheZoraiz/ascii-image-converter#14]
Hi :)

Depending on which env i run it, it can result on:

```
$ ascii-image-converter ./my_image.png

panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/TheZoraiz/ascii-image-converter/image_manipulation.ConvertToBrailleChars(0x0, 0x0, 0x0, 0x100, 0xff, 0xff, 0xff, 0x32, 0x0, 0x0, ...)
	/home/zozu/Stuff/Projects/ascii-image-converter/image_manipulation/ascii_conversions.go:180 +0xa6c
github.com/TheZoraiz/ascii-image-converter/aic_package.pathIsImage(0x7ffeae218883, 0xa, 0x0, 0x0, 0xc00000c300, 0x0, 0x0, 0x0, 0xc000010128, 0xc0000304f8, ...)
	/home/zozu/Stuff/Projects/ascii-image-converter/aic_package/convert_image.go:54 +0x2ee
github.com/TheZoraiz/ascii-image-converter/aic_package.Convert(0x7ffeae218883, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/zozu/Stuff/Projects/ascii-image-converter/aic_package/convert_root.go:157 +0x668
github.com/TheZoraiz/ascii-image-converter/cmd.glob..func1(0xd26560, 0xc0000a48c0, 0x1, 0x5)
	/home/zozu/Stuff/Projects/ascii-image-converter/cmd/root.go:97 +0x379
github.com/spf13/cobra.(*Command).execute(0xd26560, 0xc000020250, 0x5, 0x5, 0xd26560, 0xc000020250)
	/home/zozu/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xd26560, 0xc000000180, 0x200000003, 0xc000000180)
	/home/zozu/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/zozu/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/TheZoraiz/ascii-image-converter/cmd.Execute()
	/home/zozu/Stuff/Projects/ascii-image-converter/cmd/root.go:118 +0x31
main.main()
	/home/zozu/Stuff/Projects/ascii-image-converter/main.go:22 +0x25
```

In this example, i launch it on a docker ubuntu 18 running inside a linux gitlab runner.
Any idea ?

**Comment by TheZoraiz** [comment]
Hey @lepapareil

ascii-image-converter checks for console dimensions (width and height) before creating an appropriately sized ascii art. Given your error log, this might be the problem. I'm assuming this fails because you're executing the command through gitlab runner, instead of doing it manually through a console with dimensions.

There is a library-only option to prevent terminal size checking if dimensions are specified, but I can also make it a CLI flag if you want it as a feature request.

**Comment by junguler** [comment]
hello, i was just about to open an issue asking for a flag to remove dimension restrictions, i would love such an option. also can you give an option to omit output in the terminal and only save externally? it looks cool but its unnecessary for me as i use your program for batch converting image sequences.

**Comment by TheZoraiz** [comment]
@junguler Sounds like a good idea. Will implement this asap.

**Comment by TheZoraiz** [comment]
@lepapareil That actually sounds like a cleaner solution. Thanks for the input!

**Comment by junguler** [comment]
@TheZoraiz thank you, looking forward to it.

**Comment by junguler** [comment]
@TheZoraiz here it is as promised, thanks again for this great program of yours
https://github.com/junguler/_image-manipulation/tree/main/Ascii-image-converter
